# Generated by Django 5.1.5 on 2025-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_books_alter_cart_user_alter_favorite_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga/'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
