# Generated by Django 5.1.5 on 2025-01-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_image_cart_image_name_favorite_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image_name',
        ),
    ]
