# Generated by Django 5.1.5 on 2025-01-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mage_name',
            field=models.FileField(blank=True, null=True, upload_to='manga/'),
        ),
    ]
