# Generated by Django 5.1.5 on 2025-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_book_mage_name_book_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
